version: "3"
services:
  config-server:
    build:
      config-server #path with Dockerfile for config-server
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    #ports:
    # - 8888:8888 
  analyzer:
    build:
      analyzer #path with Dockerfile for analyzer
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    environment:
      - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET}
  avg-populator:
    build:
      avg-populator #path with Dockerfile for avg-populator
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    environment:
      - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET} 
      - MONGO_PASSWORD=${MONGO_PASSWORD} 
  avg-reducer:
    build:
      avg-reducer #path with Dockerfile for avg-reducer
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    environment:
      - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET} 
      - REDIS_PASSWORD=${REDIS_PASSWORD} 
  email-provider:
    build:
      email-provider #path with Dockerfile for email-data-provider
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    #ports:
    # - 8284:8284  
  email-notifier:
    build:
      email-notifier #path with Dockerfile for email-notifier
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    environment:
      - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET} 
      - MAIL_PASSWORD=${MAIL_PASSWORD}         
  range-provider:
    build:
      range-provider #path with Dockerfile for sensor-range-provider
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    #ports:
    #- 8283:8283 
  admin-console:
    build:
      admin-console #path with Dockerfile for admin-console
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET}
    #ports:
    #  - 8484:8484 
  account-provider:
    build:
      account-provider
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    #ports:
    #  - 8989:8989
  account-manager:
    build:
      account-manager
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    #ports:
    #  - 9090:9090 
    gateway:
    build:
      gateway
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 200M
    ports:
      - 9191:9191