apiVersion: apps/v1
kind: Deployment
metadata:
  name: range-provider
spec:
  selector:
    matchLabels:
      app: range-provider
  template:
    metadata:
      labels:
        app: range-provider
    spec:
      containers:
      - name: range-provider
        image: alekseid/sensor-range-provider
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
        ports:
        - containerPort: 8282
        env:
        - name: CONFIG_SERVER_HOST
          valueFrom: 
            configMapKeyRef:
              name: pm-config-map
              key: configServerHost
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongoPassword
              name: pm-secret
          
---
apiVersion: v1
kind: Service
metadata:
  name: range-provider
spec:
  selector:
    app: range-provider
  ports:
  - port: 8282
    targetPort: 8282
                    
